spring:
  application:
    name: ecosorter-backend
  datasource:
    url: jdbc:mysql://localhost:3306/ecosorter?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081

app:
  base-url: http://localhost:8081

upload:
  path: ./uploads

baidu:
  api:
    key: your_baidu_api_key
    secret: your_baidu_secret_key
    garbage:
      url: https://aip.baidubce.com/rest/2.0/image-classify/v1/garbage

file:
  upload:
    dir: ./uploads